- name: Debug mpv feature intent
  ansible.builtin.debug:
    msg:
      feature: install_mpv
      enabled: "{{ install_mpv }}"
      reason: "{{ install_mpv_reason }}"
      pkg_family: "{{ env_pkg_family }}"
      flavor: "{{ env_flavor }}"

- name: Install mpv
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_list:
      - name: "{{ env_package_names.mpv.all | default('mpv') }}"
        state: present
