# playbooks/features/install_jq.yml
- name: Debug jq feature intent
  ansible.builtin.debug:
    msg:
      feature: install_jq
      enabled: "{{ install_jq }}"
      reason: "{{ install_jq_reason }}"
      pkg_family: "{{ env_pkg_family }}"
      flavor: "{{ env_flavor }}"

- name: Install jq
  ansible.builtin.include_role:
    name: install_packages
  vars:
    install_packages_list:
      - name: "{{ env_package_names.jq.all | default('jq') }}"
        state: present
